# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'graphiti'
gem 'graphiti-rails', '~> 0.1'
gem 'image_optim'
gem 'image_processing', '~> 1.8'
gem 'kaminari'
gem 'puma', '~> 4.3.5'
gem 'pundit'
gem 'rack-cors'
gem 'rails', '~> 6.1.7.2'
gem 'shrine', '~> 3.3'
gem 'shrine-color'
gem 'xorcist'
gem 'tzinfo-data'
gem 'discard', '~> 1.2'
gem 'aws-sdk-s3', '~> 1.14'
gem 'rubyzip'
gem 'net-ssh'
gem 'ed25519', '>= 1.2', '< 2.0'
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
gem 'thor', '~> 1.1'
gem 'counter_culture', '~> 2.8'
gem 'validate_url'
gem 'pg'
gem 'good_job'
gem 'noticed'
gem 'webpush'
gem 'miro'
gem 'open3'
gem 'pony', '~> 1.13'
gem 'mato'
gem 'sanitize'
gem 'redis'
gem 'meilisearch-rails', '0.7.3'
gem 'jbuilder'
gem 'pagy', '~> 5.10'
gem 'stringex'
gem 'rack-attack'
gem 'rails_semantic_logger'

group :development, :test do
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-remote'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
