import ky from '@/lib/ky'

export const getTeamNotifications = async (teamId) => await ky.get(`team_manage/${teamId}/notifications`).json()
export const getTeamUnreadNotificationsCount = async (teamId) => await ky.get(`team_manage/${teamId}/notifications/unread_count`).json()
export const markTeamNotificationAsRead = async (teamId, notificationId) => await ky.post(`team_manage/${teamId}/notifications/${notificationId}/mark_as_read`).json()
export const markAllTeamNotificationsAsRead = async (teamId) => await ky.post(`team_manage/${teamId}/notifications/mark_all_as_read`)
export const getTeamMangas = async (teamId, keyword, page = 1, perPage = 20) => await ky.get(`team_manage/${teamId}/mangas`, { searchParams: { q: keyword, page, per_page: perPage } }).json()
export const deleteTeamManga = async (teamId, mangaId) => await ky.delete(`team_manage/${teamId}/mangas/${mangaId}`)
export const createTeamManga = async (teamId, json) => await ky.post(`team_manage/${teamId}/mangas`, { json })
export const changeChaptersOrderTeamManga = async (teamId, mangaId, json) => await ky.patch(`team_manage/${teamId}/mangas/${mangaId}/change_chapters_order`, { json })
export const getTeamManga = async (teamId, mangaId) => await ky.get(`team_manage/${teamId}/mangas/${mangaId}`).json()
export const getTeamMangaChapters = async (teamId, mangaId) => await ky.get(`team_manage/${teamId}/mangas/${mangaId}/chapters`).json()
export const updateTeamManga = async (teamId, mangaId, json) => await ky.put(`team_manage/${teamId}/mangas/${mangaId}`, { json })
export const deleteTeamChapter = async (teamId, chapterId) => await ky.delete(`team_manage/${teamId}/chapters/${chapterId}`)
export const getTeam = async (teamId) => await ky.get(`team_manage/${teamId}/team`).json()
export const updateTeam = async (teamId, json) => await ky.put(`team_manage/${teamId}/team`, { json })
export const searchTeamUsers = async (teamId, keyword, page = 1, perPage = 20) => await ky.get(`team_manage/${teamId}/users/search`, { searchParams: { q: keyword, page, per_page: perPage } }).json()
export const getTeamPosts = async (teamId, page = 1, perPage = 20) => await ky.get(`team_manage/${teamId}/team_posts`, { searchParams: { page, per_page: perPage } }).json()
export const getTeamPost = async (teamId, postId) => await ky.get(`team_manage/${teamId}/team_posts/${postId}`).json()
export const createTeamPost = async (teamId, json) => await ky.post(`team_manage/${teamId}/team_posts`, { json })
export const updateTeamPost = async (teamId, postId, json) => await ky.put(`team_manage/${teamId}/team_posts/${postId}`, { json })
export const deleteTeamPost = async (teamId, postId) => await ky.delete(`team_manage/${teamId}/team_posts/${postId}`)
