import ky from '@/lib/ky'

export const homeA = async () => await ky.get('home_a').json()
export const login = async (username, password) => await ky.post('login', { json: { username, password } }).json()
export const getUser = async () => await ky.get('user').json()
export const search = async (keyword, page = 1, perPage = 24) => await ky.get('mangas/search', { searchParams: { q: keyword, page, per_page: perPage } }).json()
export const quickSearch = async (keyword) => await ky.get('mangas/quick_search', { searchParams: { q: keyword } }).json()
export const spotlight = async () => await ky.get('mangas/spotlight').json()
export const recentlyUpdated = async (page = 1, perPage = 25) => await ky.get('mangas/recently_updated', { searchParams: { page, per_page: perPage } }).json()
export const top = async (duration = 'week', page = 1, perPage = 24) => await ky.get('mangas/top', { searchParams: { duration, page, per_page: perPage } }).json()
export const topTeams = async (duration = 'week', page = 1, perPage = 24) => await ky.get('teams/top', { searchParams: { duration, page, per_page: perPage } }).json()
export const requestResetPassword = async (json) => await ky.post('request_reset_password', { json })
export const resetPassword = async (json) => await ky.post('reset_password', { json })
export const getSuggestedMangas = async () => await ky.get('mangas/suggested').json()
export const getSuggestedTeamMangas = async (teamId) => await ky.get('mangas/suggested', { searchParams: { team_id: teamId } }).json()
export const getSuggestedMangasA = async (teamId) => await ky.get('mangas/suggested_a', { searchParams: { team_id: teamId } }).json()
export const getTag = async (slug, page, perPage = 24) => await ky.get(`tags/${slug}`, { searchParams: { page, per_page: perPage } }).json()
export const getPopularTags = async () => await ky.get('tags/popular').json()
export const searchTags = async (keyword) => await ky.get('tags/search', { searchParams: { q: keyword } }).json()
export const generateCaptcha = async () => await ky.get('generate_captcha').json()
export const register = async (json) => await ky.post('register', { json }).json()
export const createBankingOrder = async (json) => await ky.post('banking_orders', { json }).json()
export const getBankingOrder = async (id) => await ky.get(`banking_orders/${id}`).json()
export const getDonations = async (year, month) => await ky.get('donations', { searchParams: { year, month } }).json()
export const getManga = async (id) => await ky.get(`mangas/${id}`).json()
export const getChapters = async (mangaId) => await ky.get(`mangas/${mangaId}/chapters`).json()
export const getChapter = async (id) => await ky.get(`chapters/${id}`).json()
export const getComments = async (chapterId) => await ky.get(`chapters/${chapterId}/comments`).json()
export const following = async (page = 1, perPage = 24) => await ky.get('mangas/following', { searchParams: { page, per_page: perPage } }).json()
export const goFollow = async (mangaId) => await ky.post(`mangas/${mangaId}/follow`)
export const goUnfollow = async (mangaId) => await ky.delete(`mangas/${mangaId}/unfollow`)
export const getNotifications = async () => await ky.get('notifications').json()
export const getUnreadNotificationsCount = async () => await ky.get('notifications/unread_count').json()
export const markNotificationAsRead = async (notificationId) => await ky.post(`notifications/${notificationId}/mark_as_read`).json()
export const markAllNotificationsAsRead = async () => await ky.post('notifications/mark_all_as_read')
export const createComment = async (chapterId, json) => await ky.post(`chapters/${chapterId}/comments`, { json })
export const removeComment = async (commentId, json) => await ky.delete(`comments/${commentId}/remove`, { json })
export const destroyComment = async (commentId, json) => await ky.delete(`comments/${commentId}`)
export const changePassword = async (json) => await ky.post('change_password', { json })
export const createAbitraryPhoto = async (json) => await ky.post('abitrary_photos', { json }).json()
export const getTeamBySlug = async (slug) => await ky.get(`get_team_by_slug/${slug}`).json()
export const getTeam = async (teamId) => await ky.get(`teams/${teamId}`).json()
export const getTeamMangasNew = async (teamId, page = 1, perPage = 25) => await ky.get(`teams/${teamId}/mangas/recently_updated`, { searchParams: { page, per_page: perPage } }).json()
export const getTeamMangasTop = async (teamId, duration = 'week', page = 1, perPage = 25) => await ky.get(`teams/${teamId}/mangas/top`, { searchParams: { duration, page, per_page: perPage } }).json()
export const getTeamPosts = async (teamId, page = 1, perPage = 25) => await ky.get(`teams/${teamId}/team_posts`, { searchParams: { page, per_page: perPage } }).json()
export const getTeamPost = async (teamId, postId) => await ky.get(`teams/${teamId}/team_posts/${postId}`).json()
