FROM node:16-alpine as build-stage
MAINTAINER tranxuanthang<tranthang.yb@outlook.com>
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build

FROM caddy:2.2.1-alpine as serve-stage
COPY --from=build-stage /app/dist /app
COPY Caddyfile /etc/caddy/Caddyfile
EXPOSE 80
